# Imports

In [3]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Get the data

In [4]:
%pwd

'C:\\Users\\Áron\\Google Drive\\UNI\\Y4S2\\Dissertation\\dissertation-code'

In [5]:
unis_1819 = pd.read_pickle("data/unis_1819.pkl")
unis_2122 = pd.read_pickle("data/unis_2122.pkl")
summary_1819 = pd.read_pickle("data/summary_1819.pkl")
summary_2122 = pd.read_pickle("data/summary_2122.pkl")
course_1819 = pd.read_pickle("data/course_1819.pkl")
course_2122 = pd.read_pickle("data/course_2122.pkl")

In [7]:
course_2122.head()

,course,Q01,Q02,Q03,Q04,Q05,Q06,Q07,Q08,Q09,...,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27
0,"Agriculture, food and related studies",0.848417,0.796876,0.780800,0.727643,0.760136,0.814108,0.712944,0.708093,0.714422,...,0.692980,0.733963,0.733107,0.614613,0.761544,0.787482,0.704984,0.522073,0.508743,0.733192
1,"Architecture, building and planning",0.813885,0.784609,0.800091,0.787250,0.799424,0.823585,0.770105,0.666583,0.680618,...,0.687076,0.786664,0.733472,0.641516,0.795885,0.773041,0.692967,0.528990,0.503756,0.747282
2,Biological and sport sciences,0.882982,0.821448,0.828843,0.774331,0.804320,0.829850,0.758726,0.734825,0.730646,...,0.745247,0.768711,0.793037,0.646765,0.799785,0.825923,0.751016,0.593922,0.558813,0.797755
3,Business and management,0.859937,0.781681,0.794805,0.789777,0.813643,0.852627,0.789272,0.754530,0.742113,...,0.771117,0.786547,0.794266,0.662147,0.811216,0.818649,0.747880,0.613163,0.606975,0.791721
4,Combined and general studies,0.854085,0.801465,0.838083,0.746840,0.813698,0.867948,0.713996,0.676573,0.673590,...,0.671960,0.775144,0.750127,0.531346,0.726315,0.769569,0.677802,0.454758,0.421910,0.747802

# EDA

### By country